[tool.poetry]
name = "ultrack"
version = "0.1.0"
description = ""
authors = ["Jordao Bragantini <jordao.bragantini@czbiohub.org>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
rich = "^12.5.1"
magicgui = "^0.5.1"
toml = "^0.10.2"
pydantic = "^1.9.1"
higra = "^0.6.5"
zarr = "^2.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.20.0"

[tool.poetry.scripts]
ultrack = "ultrack.cli.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
