name: ultrack-stardist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - conda-forge::tensorflow
  - coin-or-cbc
  - jupyter
  - pip
  - zarr
  - pip:
    - pyqt5
    - napari
    - stardist
    - csbdeep
