name: ultrack-stardist
channels:
  - conda-forge
  - gurobi
  - defaults
dependencies:
  - python=3.9
  - rapidsai::cucim
  - conda-forge::tensorflow
  - gurobi:gurobi
  - jupyter
  - pip
  - zarr
  - pip:
    - pyqt5
    - napari
    - stardist
    - csbdeep
